# Generated by Django 4.2.24 on 2025-10-18 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliatePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='파트너 코드')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='회사명')),
                ('business_registration', models.CharField(blank=True, max_length=50, verbose_name='사업자등록번호')),
                ('phone_number', models.CharField(max_length=20, verbose_name='연락처')),
                ('website', models.URLField(blank=True, verbose_name='웹사이트')),
                ('social_media', models.JSONField(blank=True, default=dict, verbose_name='소셜미디어')),
                ('status', models.CharField(choices=[('pending', '승인대기'), ('active', '활성'), ('suspended', '일시정지'), ('terminated', '해지')], default='pending', max_length=20, verbose_name='상태')),
                ('commission_type', models.CharField(choices=[('percentage', '퍼센트'), ('fixed', '고정금액'), ('tiered', '단계별')], default='percentage', max_length=20, verbose_name='수수료 유형')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='수수료율(%)')),
                ('fixed_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='고정 수수료')),
                ('total_referrals', models.IntegerField(default=0, verbose_name='총 추천수')),
                ('total_conversions', models.IntegerField(default=0, verbose_name='총 전환수')),
                ('total_commission_earned', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='총 수수료')),
                ('total_commission_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='지급된 수수료')),
                ('minimum_payout', models.DecimalField(decimal_places=2, default=50000, max_digits=10, verbose_name='최소 지급액')),
                ('payout_method', models.CharField(default='bank_transfer', max_length=50, verbose_name='지급 방법')),
                ('bank_info', models.JSONField(blank=True, default=dict, verbose_name='은행 정보')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인일')),
                ('last_payout_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 지급일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_partner', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '홍보파트너',
                'verbose_name_plural': '홍보파트너들',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='자료명')),
                ('material_type', models.CharField(choices=[('banner', '배너'), ('text', '텍스트'), ('video', '비디오'), ('landing_page', '랜딩페이지'), ('email_template', '이메일 템플릿')], max_length=20, verbose_name='자료 유형')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('file_url', models.URLField(blank=True, verbose_name='파일 URL')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='썸네일 URL')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='가로')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='세로')),
                ('download_count', models.IntegerField(default=0, verbose_name='다운로드수')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '홍보 자료',
                'verbose_name_plural': '홍보 자료들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='링크 ID')),
                ('name', models.CharField(max_length=100, verbose_name='링크명')),
                ('target_url', models.URLField(default='/', verbose_name='타겟 URL')),
                ('utm_source', models.CharField(blank=True, max_length=100, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=100, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, verbose_name='UTM Campaign')),
                ('click_count', models.IntegerField(default=0, verbose_name='클릭수')),
                ('conversion_count', models.IntegerField(default=0, verbose_name='전환수')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to='affiliates.affiliatepartner')),
            ],
            options={
                'verbose_name': '추천 링크',
                'verbose_name_plural': '추천 링크들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 주소')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('referer', models.URLField(blank=True, verbose_name='리퍼러')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, verbose_name='클릭일시')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='세션 ID')),
                ('converted', models.BooleanField(default=False, verbose_name='전환 여부')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='전환일시')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='affiliates.referrallink')),
            ],
            options={
                'verbose_name': '추천 클릭',
                'verbose_name_plural': '추천 클릭들',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earned', '수수료 발생'), ('paid', '수수료 지급'), ('adjustment', '조정'), ('refund', '환불')], max_length=20, verbose_name='거래 유형')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='금액')),
                ('currency', models.CharField(default='KRW', max_length=10, verbose_name='통화')),
                ('reference_payment_id', models.CharField(blank=True, max_length=200, verbose_name='참조 결제 ID')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('completed', '완료'), ('failed', '실패'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='상태')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('payout_method', models.CharField(blank=True, max_length=50, verbose_name='지급 방법')),
                ('payout_reference', models.CharField(blank=True, max_length=200, verbose_name='지급 참조번호')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_transactions', to='affiliates.affiliatepartner')),
            ],
            options={
                'verbose_name': '수수료 거래',
                'verbose_name_plural': '수수료 거래들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='년도')),
                ('month', models.IntegerField(verbose_name='월')),
                ('total_clicks', models.IntegerField(default=0, verbose_name='총 클릭수')),
                ('unique_clicks', models.IntegerField(default=0, verbose_name='유니크 클릭수')),
                ('conversions', models.IntegerField(default=0, verbose_name='전환수')),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='발생 매출')),
                ('commission_earned', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='발생 수수료')),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='전환율(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_stats', to='affiliates.affiliatepartner')),
            ],
            options={
                'verbose_name': '파트너 성과',
                'verbose_name_plural': '파트너 성과들',
                'ordering': ['-year', '-month'],
                'unique_together': {('partner', 'year', 'month')},
            },
        ),
    ]
