# Generated by Django 4.2.7 on 2025-09-01 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '차트 댓글',
                'verbose_name_plural': '차트 댓글들',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChartLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '차트 좋아요',
                'verbose_name_plural': '차트 좋아요들',
            },
        ),
        migrations.CreateModel(
            name='ChartPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='현재 가격')),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='예측 가격')),
                ('prediction_date', models.DateTimeField(verbose_name='예측일')),
                ('target_date', models.DateTimeField(verbose_name='목표일')),
                ('duration_days', models.IntegerField(verbose_name='예측 기간(일)')),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='실제 가격')),
                ('accuracy_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='정확도(%)')),
                ('profit_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='수익률(%)')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('completed', '완료'), ('cancelled', '취소됨')], default='pending', max_length=20, verbose_name='상태')),
                ('is_public', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('views_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('likes_count', models.IntegerField(default=0, verbose_name='좋아요수')),
                ('comments_count', models.IntegerField(default=0, verbose_name='댓글수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '차트 예측',
                'verbose_name_plural': '차트 예측들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('start_date', models.DateTimeField(verbose_name='시작일')),
                ('end_date', models.DateTimeField(verbose_name='종료일')),
                ('prize_description', models.TextField(verbose_name='상품 설명')),
                ('status', models.CharField(choices=[('upcoming', '예정'), ('active', '진행중'), ('ended', '종료')], default='upcoming', max_length=20, verbose_name='상태')),
                ('max_participants', models.IntegerField(blank=True, null=True, verbose_name='최대 참가자 수')),
                ('participants_count', models.IntegerField(default=0, verbose_name='참가자 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '이벤트',
                'verbose_name_plural': '이벤트들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='시장명')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='시장 코드')),
                ('market_type', models.CharField(choices=[('crypto', '암호화폐'), ('kr_stock', '한국 주식'), ('us_stock', '미국 주식'), ('jp_stock', '일본 주식'), ('in_stock', '인도 주식'), ('uk_stock', '영국 주식'), ('ca_stock', '캐나다 주식'), ('fr_stock', '프랑스 주식'), ('de_stock', '독일 주식'), ('tw_stock', '대만 주식')], max_length=20, verbose_name='시장 유형')),
                ('timezone', models.CharField(default='Asia/Seoul', max_length=50, verbose_name='시간대')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
            ],
            options={
                'verbose_name': '시장',
                'verbose_name_plural': '시장들',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='심볼')),
                ('name', models.CharField(max_length=200, verbose_name='이름')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('logo_url', models.URLField(blank=True, verbose_name='로고 URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.market', verbose_name='시장')),
            ],
            options={
                'verbose_name': '종목',
                'verbose_name_plural': '종목들',
            },
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='순위')),
                ('prize_won', models.CharField(blank=True, max_length=200, verbose_name='상품')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='참가일')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.event', verbose_name='이벤트')),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.chartprediction', verbose_name='예측')),
            ],
            options={
                'verbose_name': '이벤트 참가',
                'verbose_name_plural': '이벤트 참가들',
            },
        ),
    ]
