# Generated by Django 4.2.7 on 2025-09-01 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='chartprediction',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.stock', verbose_name='종목'),
        ),
        migrations.AddField(
            model_name='chartprediction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='chartlike',
            name='prediction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.chartprediction', verbose_name='예측'),
        ),
        migrations.AddField(
            model_name='chartlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='chartcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charts.chartcomment', verbose_name='부모 댓글'),
        ),
        migrations.AddField(
            model_name='chartcomment',
            name='prediction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.chartprediction', verbose_name='예측'),
        ),
        migrations.AddField(
            model_name='chartcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('symbol', 'market')},
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipation',
            unique_together={('user', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='chartlike',
            unique_together={('user', 'prediction')},
        ),
    ]
