# Generated by Django 4.2.7 on 2025-09-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_alter_chartprediction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartprediction',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='실제 가격'),
        ),
        migrations.AlterField(
            model_name='chartprediction',
            name='current_price',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='현재 가격'),
        ),
        migrations.AlterField(
            model_name='chartprediction',
            name='predicted_price',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='예측 가격'),
        ),
    ]
