# Generated by Django 4.2.7 on 2025-09-09 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='쿠폰 코드')),
                ('name', models.CharField(max_length=100, verbose_name='쿠폰명')),
                ('coupon_type', models.CharField(choices=[('percentage', '퍼센트 할인'), ('fixed', '고정 할인'), ('free_access', '무료 이용권')], max_length=20, verbose_name='쿠폰 유형')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='할인 값')),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='최소 구매 금액')),
                ('max_usage_count', models.IntegerField(blank=True, null=True, verbose_name='최대 사용 횟수')),
                ('used_count', models.IntegerField(default=0, verbose_name='사용된 횟수')),
                ('valid_from', models.DateTimeField(verbose_name='유효 시작일')),
                ('valid_until', models.DateTimeField(verbose_name='유효 종료일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '쿠폰',
                'verbose_name_plural': '쿠폰들',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='결제 수단명')),
                ('provider', models.CharField(choices=[('paypal', 'PayPal'), ('coingate', 'CoinGate'), ('nowpayments', 'NOWPayments'), ('moonpay', 'MoonPay'), ('binance_pay', 'Binance Pay')], max_length=50, verbose_name='제공업체')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('icon_url', models.URLField(blank=True, verbose_name='아이콘 URL')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '결제 수단',
                'verbose_name_plural': '결제 수단들',
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='요금제명')),
                ('plan_type', models.CharField(choices=[('basic', '기본'), ('premium', '프리미엄'), ('pro', '프로')], max_length=20, verbose_name='요금제 유형')),
                ('price_krw', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='가격(원)')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='가격(달러)')),
                ('duration_days', models.IntegerField(verbose_name='기간(일)')),
                ('features', models.JSONField(default=list, verbose_name='기능 목록')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '결제 요금제',
                'verbose_name_plural': '결제 요금제들',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='수수료율(%)')),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='총 수수료')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to=settings.AUTH_USER_MODEL, verbose_name='피추천인')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL, verbose_name='추천인')),
            ],
            options={
                'verbose_name': '추천',
                'verbose_name_plural': '추천들',
                'unique_together': {('referrer', 'referred')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=15, verbose_name='결제 금액')),
                ('currency', models.CharField(choices=[('KRW', '한국 원'), ('USD', '미국 달러'), ('BTC', '비트코인'), ('ETH', '이더리움')], max_length=10, verbose_name='통화')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True, verbose_name='환율')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('completed', '완료'), ('failed', '실패'), ('cancelled', '취소'), ('refunded', '환불')], default='pending', max_length=20, verbose_name='결제 상태')),
                ('transaction_id', models.CharField(max_length=200, unique=True, verbose_name='거래 ID')),
                ('external_payment_id', models.CharField(blank=True, max_length=200, verbose_name='외부 결제 ID')),
                ('payment_url', models.URLField(blank=True, verbose_name='결제 URL')),
                ('callback_data', models.JSONField(blank=True, default=dict, verbose_name='콜백 데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethod', verbose_name='결제 수단')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentplan', verbose_name='요금제')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '결제',
                'verbose_name_plural': '결제들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='수수료 금액')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('paid', '지급완료'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='상태')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='지급일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payment', verbose_name='원본 결제')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.referral', verbose_name='추천')),
            ],
            options={
                'verbose_name': '수수료 지급',
                'verbose_name_plural': '수수료 지급들',
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='할인 금액')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='사용일')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.coupon', verbose_name='쿠폰')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payment', verbose_name='결제')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '쿠폰 사용 내역',
                'verbose_name_plural': '쿠폰 사용 내역들',
                'unique_together': {('user', 'coupon')},
            },
        ),
    ]
