# Generated by Django 4.2.7 on 2025-09-18 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20, verbose_name='제공업체')),
                ('event_type', models.CharField(max_length=50, verbose_name='이벤트 유형')),
                ('payment_id', models.CharField(blank=True, max_length=255, verbose_name='결제 ID')),
                ('raw_data', models.JSONField(default=dict, verbose_name='원본 데이터')),
                ('processed', models.BooleanField(default=False, verbose_name='처리 완료')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '결제 웹훅',
                'verbose_name_plural': '결제 웹훅들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='provider',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('coingate', 'CoinGate'), ('nowpayments', 'NOWPayments'), ('moonpay', 'MoonPay'), ('binance_pay', 'Binance Pay'), ('wise', 'Wise (TransferWise)'), ('skrill', 'Skrill'), ('neteller', 'Neteller')], max_length=50, verbose_name='제공업체'),
        ),
        migrations.CreateModel(
            name='InternationalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('crypto', 'Crypto Gateway')], max_length=20, verbose_name='결제 제공업체')),
                ('payment_id', models.CharField(max_length=255, unique=True, verbose_name='결제 ID')),
                ('merchant_uid', models.CharField(max_length=100, verbose_name='가맹점 거래 ID')),
                ('amount_original', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='원래 금액')),
                ('currency_original', models.CharField(default='KRW', max_length=3, verbose_name='원래 통화')),
                ('amount_converted', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='변환 금액')),
                ('currency_converted', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('KRW', 'Korean Won'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum')], max_length=3, verbose_name='변환 통화')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=15, verbose_name='환율')),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='플랫폼 수수료')),
                ('gateway_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='게이트웨이 수수료')),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='총 수수료')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('processing', '처리중'), ('completed', '완료'), ('failed', '실패'), ('cancelled', '취소'), ('refunded', '환불')], default='pending', max_length=20, verbose_name='상태')),
                ('payment_url', models.URLField(blank=True, verbose_name='결제 URL')),
                ('client_secret', models.CharField(blank=True, max_length=255, verbose_name='클라이언트 시크릿')),
                ('buyer_name', models.CharField(max_length=100, verbose_name='구매자명')),
                ('buyer_email', models.EmailField(max_length=254, verbose_name='구매자 이메일')),
                ('buyer_country', models.CharField(blank=True, max_length=2, verbose_name='구매자 국가')),
                ('product_name', models.CharField(max_length=200, verbose_name='상품명')),
                ('product_description', models.TextField(blank=True, verbose_name='상품 설명')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='게이트웨이 응답')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='메타데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='실패일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '국제 결제',
                'verbose_name_plural': '국제 결제들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3, verbose_name='기준 통화')),
                ('to_currency', models.CharField(max_length=3, verbose_name='대상 통화')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='환율')),
                ('source', models.CharField(default='manual', max_length=50, verbose_name='환율 소스')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '환율',
                'verbose_name_plural': '환율들',
                'unique_together': {('from_currency', 'to_currency')},
            },
        ),
    ]
