# Generated by Django 4.2.7 on 2025-09-01 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='심볼')),
                ('market', models.CharField(max_length=20, verbose_name='시장')),
                ('alert_type', models.CharField(choices=[('price_up', '가격 상승'), ('price_down', '가격 하락'), ('volume_spike', '거래량 급증'), ('market_open', '시장 개장'), ('market_close', '시장 마감')], max_length=20, verbose_name='알림 유형')),
                ('trigger_price', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True, verbose_name='트리거 가격')),
                ('current_price', models.DecimalField(decimal_places=8, max_digits=15, verbose_name='현재 가격')),
                ('message', models.TextField(verbose_name='메시지')),
                ('is_triggered', models.BooleanField(default=False, verbose_name='트리거됨')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='트리거일')),
            ],
            options={
                'verbose_name': '시장 알림',
                'verbose_name_plural': '시장 알림들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, verbose_name='심볼')),
                ('market', models.CharField(db_index=True, max_length=20, verbose_name='시장')),
                ('price', models.DecimalField(decimal_places=8, max_digits=15, verbose_name='가격')),
                ('volume', models.BigIntegerField(default=0, verbose_name='거래량')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='타임스탬프')),
            ],
            options={
                'verbose_name': '가격 이력',
                'verbose_name_plural': '가격 이력들',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'market', 'timestamp'], name='market_data_symbol_1f24f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, verbose_name='심볼')),
                ('market', models.CharField(choices=[('crypto', '암호화폐'), ('kr_stock', '한국 주식'), ('us_stock', '미국 주식'), ('jp_stock', '일본 주식'), ('in_stock', '인도 주식'), ('uk_stock', '영국 주식'), ('ca_stock', '캐나다 주식'), ('fr_stock', '프랑스 주식'), ('de_stock', '독일 주식'), ('tw_stock', '대만 주식')], db_index=True, max_length=20, verbose_name='시장')),
                ('current_price', models.DecimalField(decimal_places=8, max_digits=15, verbose_name='현재 가격')),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=15, verbose_name='시가')),
                ('high', models.DecimalField(decimal_places=8, max_digits=15, verbose_name='고가')),
                ('low', models.DecimalField(decimal_places=8, max_digits=15, verbose_name='저가')),
                ('volume', models.BigIntegerField(default=0, verbose_name='거래량')),
                ('change_percent', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='변화율(%)')),
                ('market_cap', models.BigIntegerField(blank=True, null=True, verbose_name='시가총액')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='타임스탬프')),
            ],
            options={
                'verbose_name': '시장 데이터',
                'verbose_name_plural': '시장 데이터들',
                'ordering': ['-timestamp'],
                'unique_together': {('symbol', 'market', 'timestamp')},
            },
        ),
    ]
