# Generated by Django 4.2.7 on 2025-09-01 13:52

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('user_type', models.CharField(choices=[('free', '무료 사용자'), ('paid', '유료 사용자'), ('admin', '관리자')], default='free', max_length=10, verbose_name='사용자 유형')),
                ('subscription_status', models.CharField(choices=[('inactive', '비활성'), ('active', '활성'), ('expired', '만료')], default='inactive', max_length=10, verbose_name='구독 상태')),
                ('free_access_count', models.IntegerField(default=0, verbose_name='무료 접근 횟수')),
                ('referral_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='추천 코드')),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='총 수익률')),
                ('prediction_accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='예측 정확도')),
                ('social_provider', models.CharField(blank=True, max_length=20, verbose_name='소셜 로그인 제공자')),
                ('social_id', models.CharField(blank=True, max_length=100, verbose_name='소셜 ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('language_preference', models.CharField(default='ko', max_length=10, verbose_name='언어 설정')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='추천인')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자들',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='프로필 사진')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='자기소개')),
                ('website', models.URLField(blank=True, verbose_name='웹사이트')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='위치')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필들',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('basic', '기본 요금제'), ('premium', '프리미엄 요금제'), ('pro', '프로 요금제')], max_length=20, verbose_name='요금제')),
                ('status', models.CharField(choices=[('active', '활성'), ('cancelled', '취소됨'), ('expired', '만료됨')], max_length=20, verbose_name='상태')),
                ('start_date', models.DateTimeField(verbose_name='시작일')),
                ('end_date', models.DateTimeField(verbose_name='종료일')),
                ('payment_id', models.CharField(blank=True, max_length=100, verbose_name='결제 ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='금액')),
                ('currency', models.CharField(default='KRW', max_length=10, verbose_name='통화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '구독',
                'verbose_name_plural': '구독들',
                'ordering': ['-created_at'],
            },
        ),
    ]
